# Generated by Django 2.0.4 on 2018-04-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70, null=True)),
                ('edad', models.PositiveIntegerField(null=True)),
                ('cc', models.PositiveIntegerField(null=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=9, null=True)),
                ('estado', models.PositiveIntegerField(default=0, null=True)),
                ('imagen', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture')),
            ],
        ),
    ]
