# Generated by Django 2.0.4 on 2018-04-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujeto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='sujeto',
            name='apellidos',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='cc',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='nombres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=9, null=True),
        ),
    ]
