# Generated by Django 2.0.4 on 2018-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujeto', '0002_auto_20180417_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujeto',
            name='apellidos',
            field=models.TextField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='nombres',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
