# Generated by Django 2.0.4 on 2018-04-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujeto', '0002_auto_20180419_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujeto',
            name='inscrito',
            field=models.NullBooleanField(default=True),
        ),
    ]
