# Generated by Django 2.0.4 on 2018-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujeto', '0003_auto_20180417_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujeto',
            name='estado',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='apellidos',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
