# Generated by Django 2.0.4 on 2018-04-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujeto_numero', models.PositiveIntegerField(null=True)),
                ('fecha_de_registro', models.DateField(null=True)),
                ('HC', models.PositiveIntegerField(null=True)),
                ('cama_numero', models.PositiveIntegerField(null=True)),
                ('fecha_evento_principal', models.DateField(null=True)),
                ('hora_evento_principal', models.TimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('G_diagnostico', models.CharField(choices=[('TCE', 'TCE'), ('Hipoxia/Anoxia', 'Hipoxia/Anoxia'), ('ACV', 'ACV')], max_length=20, null=True)),
                ('D_especificos', models.TextField(blank=True, null=True)),
                ('ci', models.CharField(choices=[('ci1', 'Paciente con episodio de parada cadíaca con reanimación exitosa'), ('ci2', 'Paciente con Dx de lesión cerebral aguda de origen traumático o evento cerebrovascular')], max_length=128, null=True)),
                ('ci3', models.NullBooleanField(verbose_name='Puntaje en escala Glasgow igual o menor a 8 después del evento inicial')),
                ('ci4', models.NullBooleanField(verbose_name='Paciente transportable a un resonador')),
                ('ce1', models.NullBooleanField(verbose_name='Diagnóstico de muerte cerebral en las primeras 48 horas del ingreso a UCI')),
                ('ce2', models.NullBooleanField(verbose_name='Destruccion masiva del parénquima cerebral no rescatable por neurocirugía')),
                ('ce3', models.NullBooleanField(verbose_name='Disfunción neurológica y/o neuropsiquiátrica previa')),
                ('ce4', models.NullBooleanField(verbose_name='Decisión de la familia de no participar en estudios de investigación')),
                ('resultado', models.NullBooleanField(verbose_name='PACIENTE APTO PARA INGRESO AL ESTUDIO')),
                ('medico_responsable', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dprevio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Traumáticos', 'Traumáticos'), ('Degenerativos', 'Degenerativos'), ('Neoplásticos', 'Neoplásticos'), ('Vasculares', 'Vasculares'), ('Infecciosos', 'Infecciosos'), ('Metabólicos', 'Metabólicos'), ('Tx Neurodesarrollo', 'Tx Neurodesarrollo'), ('TX Psicótico', 'TX Psicótico'), ('Tx Afectivo', 'Tx Afectivo'), ('Deficit cognitivo', 'Deficit cognitivo'), ('Abuso de sustancias', 'Abuso de sustancias'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='D_neuro_logico_psiquiatrico_previo',
            field=models.ManyToManyField(blank=True, to='paciente.Dprevio'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture'),
        ),
    ]
