# Generated by Django 2.0.3 on 2018-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujeto_numero', models.PositiveIntegerField()),
                ('fecha_de_registro', models.DateField()),
                ('HC', models.PositiveIntegerField()),
                ('CC', models.PositiveIntegerField()),
                ('cama_numero', models.PositiveIntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=9)),
                ('fecha_evento_principal', models.DateField()),
                ('hora_evento_principal', models.TimeField(blank=True)),
                ('G_diagnostico', models.CharField(choices=[('TCE', 'TCE'), ('Hipoxia/Anoxia', 'Hipoxia/Anoxia'), ('ACV', 'ACV')], max_length=20)),
                ('D_especificos', models.TextField(blank=True)),
                ('ci1', models.BooleanField(verbose_name='Paciente con episodio de parada cadíaca con reanimación exitosa')),
                ('ci2', models.BooleanField(verbose_name='Paciente con Dx de lesión cerebral aguda de origen traumático o evento cerebrovascular')),
                ('ci3', models.BooleanField(verbose_name='Puntaje en escala Glasgow igual o menor a 8 después del evento inicial')),
                ('ci4', models.BooleanField(verbose_name='Paciente transportable a un resonador')),
                ('ce1', models.BooleanField(verbose_name='Diagnóstico de muerte cerebral en las primeras 48 horas del ingreso a UCI')),
                ('ce2', models.BooleanField(verbose_name='Destruccion masiva del parénquima cerebral no rescatable por neurocirugía')),
                ('ce3', models.BooleanField(verbose_name='Decisión de la familia de no participar en estudios de investigación')),
                ('resultado', models.BooleanField(verbose_name='PACIENTE APTO PARA INGRESO AL ESTUDIO')),
                ('medico_responsable', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Dprevio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Traumáticos', 'Traumáticos'), ('Degenerativos', 'Degenerativos'), ('Neoplásticos', 'Neoplásticos'), ('Vasculares', 'Vasculares'), ('Infecciosos', 'Infecciosos'), ('Metabólicos', 'Metabólicos'), ('Tx Neurodesarrollo', 'Tx Neurodesarrollo'), ('TX Psicótico', 'TX Psicótico'), ('Tx Afectivo', 'Tx Afectivo'), ('Deficit cognitivo', 'Deficit cognitivo'), ('Abuso de sustancias', 'Abuso de sustancias'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='D_neuro_logico_psiquiatrico_previo',
            field=models.ManyToManyField(blank=True, to='paciente.Dprevio'),
        ),
    ]
