# Generated by Django 2.0.4 on 2018-04-27 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apatologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('HTA', 'HTA'), ('Diabetes', 'Diabetes'), ('IAM', 'IAM'), ('Hipotiroidismo', 'Hipotiroidismo'), ('Dislipidemia', 'Dislipidemia'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujeto_numero', models.PositiveIntegerField(null=True, unique=True)),
                ('fecha_de_registro', models.DateField(default=datetime.date.today, null=True)),
                ('cc', models.PositiveIntegerField(null=True, unique=True)),
                ('nombres', models.CharField(max_length=70, null=True)),
                ('apellidos', models.CharField(max_length=70, null=True)),
                ('edad', models.PositiveIntegerField(null=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=9, null=True)),
                ('HC', models.PositiveIntegerField(null=True, unique=True)),
                ('cama_numero', models.PositiveIntegerField(null=True)),
                ('fecha_evento_principal', models.DateField(default=datetime.date.today, null=True)),
                ('hora_evento_principal', models.TimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('G_diagnostico', models.CharField(choices=[('TCE', 'TCE'), ('Hipoxia/Anoxia', 'Hipoxia/Anoxia'), ('ACV', 'ACV')], max_length=20, null=True)),
                ('D_especificos', models.TextField(blank=True, null=True)),
                ('ci', models.CharField(choices=[('ci1', 'Paciente con episodio de parada cadíaca con reanimación exitosa'), ('ci2', 'Paciente con Dx de lesión cerebral aguda de origen traumático o evento cerebrovascular')], max_length=128, null=True)),
                ('ci3', models.NullBooleanField(verbose_name='Puntaje en escala Glasgow igual o menor a 8 después del evento inicial')),
                ('ci4', models.NullBooleanField(verbose_name='Paciente transportable a un resonador')),
                ('ce1', models.NullBooleanField(verbose_name='Diagnóstico de muerte cerebral en las primeras 48 horas del ingreso a UCI')),
                ('ce2', models.NullBooleanField(verbose_name='Destruccion masiva del parénquima cerebral no rescatable por neurocirugía')),
                ('ce3', models.NullBooleanField(verbose_name='Disfunción neurológica y/o neuropsiquiátrica previa')),
                ('ce4', models.NullBooleanField(verbose_name='Decisión de la familia de no participar en estudios de investigación')),
                ('estado', models.PositiveIntegerField(default=1, null=True)),
                ('inscrito', models.NullBooleanField(default=False)),
            ],
            options={
                'ordering': ('sujeto_numero',),
            },
        ),
        migrations.CreateModel(
            name='Dprevio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Traumáticos', 'Traumáticos'), ('Degenerativos', 'Degenerativos'), ('Neoplásticos', 'Neoplásticos'), ('Vasculares', 'Vasculares'), ('Infecciosos', 'Infecciosos'), ('Metabólicos', 'Metabólicos'), ('Tx Neurodesarrollo', 'Tx Neurodesarrollo'), ('TX Psicótico', 'TX Psicótico'), ('Tx Afectivo', 'Tx Afectivo'), ('Deficit cognitivo', 'Deficit cognitivo'), ('Abuso de sustancias', 'Abuso de sustancias'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_form', models.DateField(default=datetime.date.today, null=True)),
                ('lugar_nacimiento', models.CharField(max_length=80, null=True)),
                ('lugar_residencia', models.CharField(max_length=80, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('nombre_acompanante', models.CharField(max_length=70, null=True)),
                ('tel1', models.PositiveIntegerField(null=True)),
                ('tel2', models.PositiveIntegerField(null=True)),
                ('peso', models.PositiveIntegerField(null=True)),
                ('estatura', models.PositiveIntegerField(null=True)),
                ('n_educativo', models.CharField(choices=[('Primaria', 'Primaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Profesional', 'Profesional')], max_length=20, null=True)),
                ('lateralidad', models.CharField(choices=[('Diestro', 'Diestro'), ('Zurdo', 'Zurdo'), ('Ambidiestro', 'Ambidiestro')], max_length=20, null=True)),
                ('conciencia', models.CharField(choices=[('Coma', 'Coma'), ('SVSR', 'SVSR'), ('EMC', 'EMC')], max_length=20, null=True)),
                ('sedado', models.NullBooleanField(verbose_name='Sedado por neuroprotección')),
                ('a_patologicos_cual', models.CharField(max_length=50, null=True)),
                ('quirurgicos', models.CharField(choices=[('craneotomia', 'Craneotomía'), ('otro', 'Otro')], max_length=128, null=True)),
                ('fecha_craneotomia', models.DateField(blank=True, null=True)),
                ('causa_quirurgicos', models.CharField(blank=True, max_length=100, null=True)),
                ('a_toxico_alergenicos', models.CharField(blank=True, max_length=180, null=True)),
                ('a_farmaco1', models.CharField(blank=True, max_length=180, null=True)),
                ('a_farmaco1_dosis', models.CharField(blank=True, max_length=30, null=True)),
                ('a_farmaco2', models.CharField(blank=True, max_length=180, null=True)),
                ('a_farmaco2_dosis', models.CharField(blank=True, max_length=30, null=True)),
                ('a_familiares', models.CharField(blank=True, max_length=180, null=True)),
                ('firma_consentimiento', models.BooleanField(default=True)),
                ('firma_causa', models.CharField(blank=True, max_length=50, null=True)),
                ('a_patologicos', models.ManyToManyField(blank=True, to='paciente.Apatologicos')),
                ('candidato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='D_neuro_logico_psiquiatrico_previo',
            field=models.ManyToManyField(blank=True, to='paciente.Dprevio'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='medico_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
    ]
