# Generated by Django 2.0.4 on 2018-04-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='resultado',
        ),
        migrations.AddField(
            model_name='candidato',
            name='apellidos',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='cc',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='inscrito',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nombres',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='HC',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci3',
            field=models.NullBooleanField(default=True, verbose_name='Puntaje en escala Glasgow igual o menor a 8 después del evento inicial'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci4',
            field=models.NullBooleanField(default=True, verbose_name='Paciente transportable a un resonador'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='medico_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sujeto_numero',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
