# Generated by Django 2.0.4 on 2018-05-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='document',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
