# Generated by Django 2.0.4 on 2018-06-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='archivo',
            field=models.FileField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='archivo',
            field=models.FileField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='archivofirma',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
