# Generated by Django 2.0.4 on 2018-04-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='CC',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='sexo',
        ),
    ]
