# Generated by Django 2.0.4 on 2018-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='candidato',
            name='medico_responsable',
            field=models.ForeignKey(null=True, on_delete=None, to='paciente.Medico'),
        ),
    ]
