# Generated by Django 2.0.4 on 2018-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['-inscrito']},
        ),
        migrations.AddField(
            model_name='uci',
            name='fallaorganica',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='fallaorganica_cual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
