# Generated by Django 2.0.4 on 2018-04-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='sujeto_numero',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
