# Generated by Django 2.0.4 on 2018-04-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
        ('paciente', '0002_auto_20180417_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='imagen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture'),
        ),
    ]
