# Generated by Django 2.0.4 on 2018-05-02 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20180501_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='uci',
            name='acido_valproico',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='acido_valproico_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='adrenalina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='apertura_ocular_e',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='carbamacepina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='carbamacepina_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='carbonato_litio',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='carbonato_litio_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='causa_mortalidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='clozapina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='clozapina_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='condicion_egreso',
            field=models.CharField(choices=[('Vivo', 'Vivo'), ('Remitido', 'Remitido'), ('Fallecido', 'Fallecido')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='continua_studio',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='dexmedetomidina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='dexmedetomidina_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='dx_egreso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='fechaegreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='fechamortalidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='fenitoina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='fenitoina_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='fentanyl',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='fentanyl_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='glasgowtotal_e',
            field=models.CharField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='haloperidol',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='haloperidol_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='hidromorfona',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='hidromorfona_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='horaegreso',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='horamortalidad',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='ketiapina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='ketiapina_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='lacosamida',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='lacosamida_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='levetiracetam',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='levetiracetam_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='midazolan',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='midazolan_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='monitoria_pic',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='morfina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='morfina_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='noradrenalina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='presion_intracraneana',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='respuesta_motora_e',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='respuesta_verbal_e',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='sepsis',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='soportevasopresor',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='tiopental',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='tiopental_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='topiramato',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='topiramato_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='valorable_neuro',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='valorable_neuro_causa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='vasopresina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uci',
            name='ventilacionmecanica',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='fallaorganica_cual',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
