# Generated by Django 2.0.4 on 2018-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20180520_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='archivo',
            field=models.FileField(null=True, upload_to='Documentos'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='archivofirma',
            field=models.FileField(blank=True, null=True, upload_to='Documentos'),
        ),
    ]
