# Generated by Django 2.0.4 on 2018-04-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20180419_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='HC',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='medico_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sujeto_numero',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
