# Generated by Django 2.0.4 on 2018-05-21 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20180520_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uci',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato'),
        ),
    ]
