# Generated by Django 2.0.4 on 2018-04-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sujeto', '0003_sujeto_inscrito'),
        ('paciente', '0003_auto_20180419_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='resultado',
        ),
        migrations.AddField(
            model_name='candidato',
            name='sujeto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sujeto.Sujeto'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci3',
            field=models.NullBooleanField(default=True, verbose_name='Puntaje en escala Glasgow igual o menor a 8 después del evento inicial'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci4',
            field=models.NullBooleanField(default=True, verbose_name='Paciente transportable a un resonador'),
        ),
    ]
