# Generated by Django 2.0.4 on 2018-05-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20180501_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uci',
            name='condicion_egreso',
            field=models.CharField(blank=True, choices=[('Vivo', 'Vivo'), ('Remitido', 'Remitido'), ('Fallecido', 'Fallecido')], max_length=100, null=True),
        ),
    ]
