# Generated by Django 2.0.4 on 2018-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_candidato_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='quirurgicos',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='hora_evento_principal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='a_patologicos_cual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nombre_acompanante',
            field=models.CharField(default='', max_length=70, null=True),
        ),
    ]
