# Generated by Django 2.0.4 on 2018-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20180610_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uci',
            name='acido_valproico',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='carbamacepina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='carbonato_litio',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='clozapina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='dexmedetomidina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='fenitoina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='fentanyl',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='haloperidol',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='hidromorfona',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='ketiapina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='lacosamida',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='levetiracetam',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='midazolan',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='morfina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='tiopental',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='topiramato',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
    ]
