# Generated by Django 2.0.4 on 2018-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_candidato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='D_especificos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='G_diagnostico',
            field=models.CharField(choices=[('TCE', 'TCE'), ('Hipoxia/Anoxia', 'Hipoxia/Anoxia'), ('ACV', 'ACV')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='HC',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cama_numero',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fecha_de_registro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fecha_evento_principal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='hora_evento_principal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='medico_responsable',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sujeto_numero',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
