# Generated by Django 2.0.4 on 2018-04-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20180421_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sujeto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sujeto.Sujeto'),
        ),
    ]
