# Generated by Django 2.0.4 on 2018-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20180512_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fechafirma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='adrenalina',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='horauci',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='noradrenalina',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='vasopresina',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
    ]
