# Generated by Django 2.0.4 on 2018-04-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20180417_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='ce1',
            field=models.NullBooleanField(verbose_name='Diagnóstico de muerte cerebral en las primeras 48 horas del ingreso a UCI'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ce2',
            field=models.NullBooleanField(verbose_name='Destruccion masiva del parénquima cerebral no rescatable por neurocirugía'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ce3',
            field=models.NullBooleanField(verbose_name='Decisión de la familia de no participar en estudios de investigación'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci1',
            field=models.NullBooleanField(verbose_name='Paciente con episodio de parada cadíaca con reanimación exitosa'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci2',
            field=models.NullBooleanField(verbose_name='Paciente con Dx de lesión cerebral aguda de origen traumático o evento cerebrovascular'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci3',
            field=models.NullBooleanField(verbose_name='Puntaje en escala Glasgow igual o menor a 8 después del evento inicial'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ci4',
            field=models.NullBooleanField(verbose_name='Paciente transportable a un resonador'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='resultado',
            field=models.NullBooleanField(verbose_name='PACIENTE APTO PARA INGRESO AL ESTUDIO'),
        ),
    ]
