# Generated by Django 2.0.4 on 2018-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20180501_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='fechafirma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
