# Generated by Django 2.0.4 on 2018-05-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20180513_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologia',
            name='monitoreo',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='radiologia',
            name='radiologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
        migrations.AlterField(
            model_name='neurologia',
            name='resultadoeeg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='dx_egreso',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='horaegreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uci',
            name='horamortalidad',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
