# Generated by Django 2.0.4 on 2018-05-05 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_ingreso_fechafirma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neurologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaneuro', models.DateField(null=True)),
                ('candidato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
                ('neurologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico')),
            ],
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='conciencia',
            field=models.CharField(choices=[('Coma', 'Coma'), ('SVSR', 'SVSR'), ('EMC', 'EMC')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fechafirma',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='lateralidad',
            field=models.CharField(choices=[('Diestro', 'Diestro'), ('Zurdo', 'Zurdo'), ('Ambidiestro', 'Ambidiestro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='lugar_nacimiento',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='lugar_residencia',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='n_educativo',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Profesional', 'Profesional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nombre_acompanante',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tel1',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
