# Generated by Django 2.0.4 on 2018-04-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20180417_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture'),
        ),
    ]
