# Generated by Django 2.0.4 on 2018-06-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20180607_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='ci',
            field=models.CharField(choices=[('ci1', 'Paciente con episodio de parada cardíaca con reanimación exitosa'), ('ci2', 'Paciente con Dx de lesión cerebral aguda de origen traumático o evento cerebrovascular')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
