# Generated by Django 2.0.4 on 2018-06-18 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20180618_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 15, 35, 11, 332369), null=True),
        ),
    ]
