# Generated by Django 2.0.4 on 2018-06-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20180618_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(null=True),
        ),
    ]
