# Generated by Django 2.0.4 on 2018-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20180607_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
