# Generated by Django 2.0.4 on 2018-05-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_neurologia_auditiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neurologia',
            name='auditiva',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, null=True),
        ),
    ]
