# Generated by Django 2.0.4 on 2018-05-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_bold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='axt2prop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='axt2prop_opciones',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=20, null=True),
        ),
    ]
