# Generated by Django 2.0.4 on 2018-06-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20180618_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
