# Generated by Django 2.0.4 on 2018-05-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_auto_20180513_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bold',
            name='axt2prop_opciones',
        ),
        migrations.AddField(
            model_name='bold',
            name='axt2prop1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='axt2prop2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='axt2prop3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='axt2prop4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='axt2prop5',
            field=models.BooleanField(default=False),
        ),
    ]
