# Generated by Django 2.0.4 on 2018-05-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20180513_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='difussion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussion1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussion2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussion3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussion4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussion5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussion6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussion7',
            field=models.BooleanField(default=False),
        ),
    ]
