# Generated by Django 2.0.4 on 2018-06-19 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uci',
            name='candidato',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato'),
        ),
    ]
