# Generated by Django 2.0.4 on 2018-05-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_auto_20180514_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='resting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='resting8',
            field=models.BooleanField(default=False),
        ),
    ]
