# Generated by Django 2.0.4 on 2018-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_auto_20180609_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.FileField(null=True, upload_to='Archivos'),
        ),
    ]
