# Generated by Django 2.0.4 on 2018-05-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_auto_20180514_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='obl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='obl1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='obl2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='obl3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='obl4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='obl5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='obl6',
            field=models.BooleanField(default=False),
        ),
    ]
