# Generated by Django 2.0.4 on 2018-05-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_auto_20180505_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurologia',
            name='estadoconciencia',
            field=models.CharField(choices=[('Coma', 'Coma'), ('Vigilia_sin_respuesta', 'Vigilia_sin_respuesta'), ('Mínima_conciencia', 'Mínima_conciencia')], max_length=30, null=True),
        ),
    ]
