# Generated by Django 2.0.4 on 2018-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20180514_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='flair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flair1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flair2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flair3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flair4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flair5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flair6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flair7',
            field=models.BooleanField(default=False),
        ),
    ]
