# Generated by Django 2.0.4 on 2018-05-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_neurologia_estadoconciencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurologia',
            name='epileptico',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='neurologia',
            name='fechaeeg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neurologia',
            name='resultadoeeg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='neurologia',
            name='segunda',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='neurologia',
            name='estadoconciencia',
            field=models.CharField(choices=[('Coma', 'Coma'), ('Vigilia_sin_respuesta', 'Vigilia sin respuesta'), ('Mínima_conciencia', 'Mínima conciencia')], max_length=30, null=True),
        ),
    ]
