# Generated by Django 2.0.4 on 2018-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_auto_20180514_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='cal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='cal1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='cal2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='cal3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='cal4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='cal5',
            field=models.BooleanField(default=False),
        ),
    ]
