# Generated by Django 2.0.4 on 2018-06-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_auto_20180618_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='ci',
            field=models.CharField(blank=True, choices=[('ci1', 'Paciente con episodio de parada cardíaca con reanimación exitosa'), ('ci2', 'Paciente con Dx de lesión cerebral aguda de origen traumático o evento cerebrovascular')], default='ci1', max_length=128, null=True),
        ),
    ]
