# Generated by Django 2.0.4 on 2018-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_auto_20180514_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='swi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='swi8',
            field=models.BooleanField(default=False),
        ),
    ]
