# Generated by Django 2.0.4 on 2018-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_auto_20180514_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='tensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensor8',
            field=models.BooleanField(default=False),
        ),
    ]
