# Generated by Django 2.0.4 on 2018-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0016_auto_20180619_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='infeccion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='infeccion_foco',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
