# Generated by Django 2.0.4 on 2018-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_bold_t1a'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='difusionA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difusionM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flairA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='flairM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='t1G',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='t1M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='t2A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='t2M',
            field=models.BooleanField(default=False),
        ),
    ]
