# Generated by Django 2.0.4 on 2018-06-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_auto_20180619_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='parada',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='parada_tiempo',
            field=models.PositiveIntegerField(blank=0, null=True),
        ),
    ]
