# Generated by Django 2.0.4 on 2018-06-20 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0018_auto_20180619_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fechaseguimiento',
            field=models.DateField(default=datetime.date(2018, 6, 19), null=True),
        ),
    ]
