# Generated by Django 2.0.4 on 2018-05-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0018_auto_20180514_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bold',
            name='cd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussionA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='difussionM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
        migrations.AddField(
            model_name='bold',
            name='restingA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='restingG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='restingM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='restingT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='restingV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensorA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensorG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensorM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bold',
            name='tensord',
            field=models.BooleanField(default=False),
        ),
    ]
