# Generated by Django 2.0.4 on 2018-06-20 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0019_auto_20180619_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fechaseguimiento',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
