# Generated by Django 2.0.4 on 2018-05-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0019_auto_20180514_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrevista', models.DateField(null=True)),
                ('candidato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
                ('neuropsicologa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico')),
            ],
        ),
    ]
