# Generated by Django 2.0.4 on 2018-06-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0021_auto_20180619_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='pic',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='pic_numero',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='ventilacion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True),
        ),
    ]
