# Generated by Django 2.0.4 on 2018-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0021_informante'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor',
            name='confiable',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='informante',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='parentezco',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
