# Generated by Django 2.0.4 on 2018-06-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0022_auto_20180619_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='dexmedeto',
            field=models.CharField(default=0, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fentanyl',
            field=models.CharField(default=0, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='midazolam',
            field=models.CharField(default=0, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='neuroimagen',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='neurologia',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='soporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='soporte_cual',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tiopental',
            field=models.CharField(default=0, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='vecuronio',
            field=models.CharField(default=0, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fallaorganica',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='infeccion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='parada',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='pic',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='ventilacion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True),
        ),
    ]
