# Generated by Django 2.0.4 on 2018-05-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0023_auto_20180514_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informante',
            name='neuropsicologa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
    ]
