# Generated by Django 2.0.4 on 2018-06-20 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0023_auto_20180619_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha_de_registro',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
