# Generated by Django 2.0.4 on 2018-05-15 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0024_auto_20180514_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informante',
            name='neuropsicologa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
    ]
