# Generated by Django 2.0.4 on 2018-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0024_auto_20180619_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='apellidos',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombres',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='direccion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nombre_acompanante',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
