# Generated by Django 2.0.4 on 2018-06-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0025_auto_20180620_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='a_farmaco1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='a_toxico_alergenicos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
