# Generated by Django 2.0.4 on 2018-05-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0025_auto_20180514_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor',
            name='archivo',
            field=models.FileField(null=True, upload_to='a'),
        ),
    ]
