# Generated by Django 2.0.4 on 2018-05-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0026_mayor_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mayor',
            name='archivo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='archivo',
            field=models.FileField(null=True, upload_to='Documentos/<django.db.models.fields.CharField>'),
        ),
    ]
