# Generated by Django 2.0.4 on 2018-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0026_auto_20180620_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='lugar_nacimiento',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='lugar_residencia',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
