# Generated by Django 2.0.4 on 2018-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0027_auto_20180620_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='a_familiares',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='a_farmaco1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='a_farmaco2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='a_toxico_alergenicos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
