# Generated by Django 2.0.4 on 2018-05-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0027_auto_20180514_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='archivo',
            field=models.FileField(null=True, upload_to='Documentos'),
        ),
    ]
