# Generated by Django 2.0.4 on 2018-05-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0028_auto_20180514_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor',
            name='cambio1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
    ]
