# Generated by Django 2.0.4 on 2018-06-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0028_auto_20180620_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neurologia',
            name='resultadoeeg',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ur_pulsoximetro_sv',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
