# Generated by Django 2.0.4 on 2018-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0029_mayor_cambio1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor',
            name='cambio2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='resultado',
            field=models.CharField(default='Mejoría', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='total',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
