# Generated by Django 2.0.4 on 2018-06-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0029_auto_20180622_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologia',
            name='analgesia_sv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='relajacion_sv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ru_frecuencia_cardiaca_sv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ru_frecuencia_respiratoria_sv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ru_pulsoximetro_sv',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ru_tension_sv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ru_visoscopio_sv',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='sedacion_sv',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='svadicional2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ur_frecuencia_cardiaca_sv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ur_frecuencia_respiratoria_sv',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ur_tension_sv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ur_visoscopio_sv',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
