# Generated by Django 2.0.4 on 2018-06-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0030_auto_20180622_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologia',
            name='complicaciones_cuales',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='me_cual',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='me_dosis',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='pic',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ppc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
