# Generated by Django 2.0.4 on 2018-05-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0030_auto_20180515_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor',
            name='cambio10',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio11',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio12',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio13',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio14',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio15',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio16',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio17',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio18',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio19',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio20',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio21',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio22',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio23',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio24',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio25',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio26',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio3',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio4',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio5',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio6',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio7',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio8',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='cambio9',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
    ]
