# Generated by Django 2.0.4 on 2018-06-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0031_auto_20180622_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayor',
            name='tiempo',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
