# Generated by Django 2.0.4 on 2018-05-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0031_auto_20180515_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor',
            name='dxdemencia',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='severidadgds',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mayor',
            name='tiempo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
