# Generated by Django 2.0.4 on 2018-06-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0032_auto_20180622_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='medico_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
    ]
