# Generated by Django 2.0.4 on 2018-06-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0033_seguimiento_medico_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neurologia',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato'),
        ),
    ]
