# Generated by Django 2.0.4 on 2018-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0034_auto_20180625_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=True, unique=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
