# Generated by Django 2.0.4 on 2018-06-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0036_auto_20180630_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='controles'),
        ),
    ]
