# Generated by Django 2.0.4 on 2018-07-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0038_cambioradiologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioradiologia',
            name='razon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
