# Generated by Django 2.0.4 on 2018-07-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0039_cambioradiologia_razon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neurologia',
            name='segunda',
        ),
    ]
