# Generated by Django 2.0.4 on 2018-07-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0040_remove_neurologia_segunda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioradiologia',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
