# Generated by Django 2.0.4 on 2018-07-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0041_auto_20180705_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'permissions': (('can_descargar', 'puede descargar candidato'),)},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['numero'], 'permissions': (('can_descargar', 'puede descargar control'),)},
        ),
    ]
