# Generated by Django 2.0.4 on 2018-07-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0042_auto_20180706_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'permissions': (('can_descargar_candidato', 'puede descargar candidato'),)},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['numero'], 'permissions': (('can_descargar_control', 'puede descargar control'),)},
        ),
    ]
