# Generated by Django 2.0.4 on 2018-07-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0043_auto_20180706_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'permissions': (('can_ver_ingreso', 'puede ver ingreso'),)},
        ),
    ]
