# Generated by Django 2.0.4 on 2018-07-07 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0044_auto_20180706_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bold',
            options={'permissions': (('can_ver_bold', 'puede ver bold'),)},
        ),
        migrations.AlterModelOptions(
            name='informante',
            options={'permissions': (('can_ver_informante', 'puede ver informante'),)},
        ),
        migrations.AlterModelOptions(
            name='neurologia',
            options={'permissions': (('can_ver_neurologia', 'puede ver neurologia'),)},
        ),
        migrations.AlterModelOptions(
            name='radiologia',
            options={'permissions': (('can_ver_radiologia', 'puede ver radiologia'),)},
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'permissions': (('can_ver_seguimiento', 'puede ver seguimiento'),)},
        ),
        migrations.AlterModelOptions(
            name='uci',
            options={'permissions': (('can_ver_uci', 'puede ver uci'),)},
        ),
    ]
