# Generated by Django 2.0.4 on 2018-07-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0045_auto_20180706_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='abstraccion',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='atencion_letras',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='atencion_numero',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='atencion_resta',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='funcion_visoespacial',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='identificacion',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='lenguaje_fluidez',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='lenguaje_repite',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='orientacion',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='recuerdo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='total',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
