# Generated by Django 2.0.4 on 2018-07-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0046_auto_20180711_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('funcion_visoespacial', models.CharField(max_length=1, null=True)),
                ('identificacion', models.CharField(max_length=1, null=True)),
                ('atencion_numero', models.CharField(max_length=1, null=True)),
                ('atencion_letras', models.CharField(max_length=1, null=True)),
                ('atencion_resta', models.CharField(max_length=1, null=True)),
                ('lenguaje_repite', models.CharField(max_length=1, null=True)),
                ('lenguaje_fluidez', models.CharField(max_length=1, null=True)),
                ('abstraccion', models.CharField(max_length=1, null=True)),
                ('recuerdo', models.CharField(max_length=1, null=True)),
                ('orientacion', models.CharField(max_length=1, null=True)),
                ('total', models.CharField(max_length=2, null=True)),
                ('candidato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
            ],
            options={
                'permissions': (('can_ver_moca', 'puede ver moca'),),
            },
        ),
        migrations.AddField(
            model_name='control',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
