# Generated by Django 2.0.4 on 2018-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0047_auto_20180711_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='direccion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
