# Generated by Django 2.0.4 on 2018-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0049_auto_20180718_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='ci',
            field=models.CharField(blank=True, choices=[('Paciente con episodio de parada cardíaca con reanimación exitosa', 'Paciente con episodio de parada cardíaca con reanimación exitosa'), ('Paciente con Dx de lesión cerebral aguda de origen traumático', 'Paciente con Dx de lesión cerebral aguda de origen traumático'), ('Paciente con Dx de lesión cerebral aguda por evento cerebrovascular', 'Paciente con Dx de lesión cerebral aguda por evento cerebrovascular')], default='Paciente con episodio de parada cardíaca con reanimación exitosa', max_length=128, null=True),
        ),
    ]
