# Generated by Django 2.0.4 on 2018-07-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0050_auto_20180719_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologia',
            name='ru_tension_sv',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='svadicional2',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='radiologia',
            name='ur_tension_sv',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
