# Generated by Django 2.0.4 on 2018-07-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0052_auto_20180724_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bold',
            name='difusionA',
        ),
        migrations.RemoveField(
            model_name='bold',
            name='difusionM',
        ),
    ]
