# Generated by Django 2.0.4 on 2018-07-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0053_auto_20180726_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valorablenps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorable', models.BooleanField()),
                ('sujeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
            ],
        ),
        migrations.AlterField(
            model_name='moca',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato'),
        ),
    ]
