# Generated by Django 2.0.4 on 2018-07-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0054_auto_20180726_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorablenps',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
