# Generated by Django 2.0.4 on 2018-07-27 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0055_valorablenps_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorablenps',
            name='sujeto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato'),
        ),
    ]
