# Generated by Django 2.0.4 on 2018-07-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0056_auto_20180726_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moca',
            options={'ordering': ['fecha'], 'permissions': (('can_ver_moca', 'puede ver moca'),)},
        ),
    ]
