# Generated by Django 2.0.4 on 2018-07-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0058_auto_20180727_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorablenps',
            name='razon',
            field=models.CharField(choices=[('Fallecido', 'Fallecido'), ('No localizable', 'No localizable'), ('No colabora', 'No colabora'), ('EMC', 'EMC'), ('SVSR', 'SVSR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fallaorganica_cual',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='infeccion_foco',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
