# Generated by Django 2.0.4 on 2018-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0059_auto_20180727_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorablenps',
            name='valorable',
            field=models.NullBooleanField(),
        ),
    ]
