# Generated by Django 2.0.4 on 2018-07-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0060_auto_20180727_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorablenps',
            name='fechafallecido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valorablenps',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
