# Generated by Django 2.0.4 on 2018-08-07 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0062_control_n_educativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neuropsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('medicado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=12, null=True)),
                ('medicado_cual', models.CharField(blank=True, max_length=180, null=True)),
                ('medicado_dt', models.CharField(blank=True, max_length=180, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('orientacion_tiempo', models.CharField(max_length=1, null=True)),
                ('orientacion_espacio', models.CharField(max_length=1, null=True)),
                ('orientacion_persona', models.CharField(max_length=1, null=True)),
                ('orientacion', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('atencion_digitos', models.CharField(max_length=1, null=True)),
                ('atencion_visual', models.CharField(max_length=2, null=True)),
                ('atencion_20_3', models.CharField(max_length=1, null=True)),
                ('atencion', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('codificacion_palabras', models.CharField(max_length=1, null=True)),
                ('codificacion_figura', models.CharField(max_length=3, null=True)),
                ('codificacion', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('evocacion_figura', models.CharField(max_length=3, null=True)),
                ('evocacion_espontanea', models.CharField(max_length=1, null=True)),
                ('evocacion_claves', models.CharField(max_length=1, null=True)),
                ('evocacion_reconocimiento', models.CharField(max_length=1, null=True)),
                ('evocacion', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('lenguaje_denominacion', models.CharField(max_length=1, null=True)),
                ('lenguaje_repeticion', models.CharField(max_length=1, null=True)),
                ('lenguaje_comprension', models.CharField(max_length=1, null=True)),
                ('lenguaje_semantica', models.CharField(max_length=2, null=True)),
                ('lenguaje_fonologica', models.CharField(max_length=2, null=True)),
                ('lenguaje', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('lectura_lectura', models.CharField(max_length=1, null=True)),
                ('lectura_dictado', models.CharField(max_length=1, null=True)),
                ('lectura_copiado', models.CharField(max_length=1, null=True)),
                ('lectura', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('conceptual_semejanzas', models.CharField(max_length=1, null=True)),
                ('conceptual_calculo', models.CharField(max_length=1, null=True)),
                ('conceptual_secuenciacion', models.CharField(max_length=1, null=True)),
                ('conceptual', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('motora_mano_der', models.CharField(max_length=1, null=True)),
                ('motora_mano_izq', models.CharField(max_length=1, null=True)),
                ('motora_alternos', models.CharField(max_length=1, null=True)),
                ('motora_reacciones', models.CharField(max_length=1, null=True)),
                ('motora', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('resultado', models.CharField(choices=[('Normal Alto', 'Normal Alto'), ('Normal', 'Normal'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], max_length=15, null=True)),
                ('candidato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
            ],
        ),
        migrations.AlterField(
            model_name='control',
            name='n_educativo',
            field=models.CharField(choices=[('Analfabeta', 'Analfabeta'), ('Primaria', 'Primaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Profesional', 'Profesional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='n_educativo',
            field=models.CharField(choices=[('Analfabeta', 'Analfabeta'), ('Primaria', 'Primaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Profesional', 'Profesional')], max_length=20, null=True),
        ),
    ]
