# Generated by Django 2.0.4 on 2018-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0063_auto_20180806_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuropsi',
            name='codificacion_figura',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='neuropsi',
            name='evocacion_figura',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
