# Generated by Django 2.0.4 on 2018-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0064_auto_20180807_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='soporte_cual',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
