# Generated by Django 2.0.4 on 2018-08-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0065_auto_20180823_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametrosimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeimg', models.CharField(max_length=50, null=True)),
                ('FieldOfViewDimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('SliceThickness', models.CharField(blank=True, max_length=50, null=True)),
                ('SpacingBetweenSlices', models.CharField(blank=True, max_length=50, null=True)),
                ('RepetitionTime', models.CharField(blank=True, max_length=50, null=True)),
                ('PercentPhaseFieldOfView', models.CharField(blank=True, max_length=50, null=True)),
                ('volumes', models.CharField(blank=True, max_length=50, null=True)),
                ('sujeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
            ],
            options={
                'permissions': (('can_ver_parametrosimg', 'puede ver parametrosimg'),),
            },
        ),
        migrations.CreateModel(
            name='Parametrosimgcontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeimg', models.CharField(max_length=50, null=True)),
                ('FieldOfViewDimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('SliceThickness', models.CharField(blank=True, max_length=50, null=True)),
                ('SpacingBetweenSlices', models.CharField(blank=True, max_length=50, null=True)),
                ('RepetitionTime', models.CharField(blank=True, max_length=50, null=True)),
                ('PercentPhaseFieldOfView', models.CharField(blank=True, max_length=50, null=True)),
                ('volumes', models.CharField(blank=True, max_length=50, null=True)),
                ('sujeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Control')),
            ],
        ),
    ]
