# Generated by Django 2.0.4 on 2018-08-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0066_parametrosimg_parametrosimgcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametrosmotioncorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute', models.CharField(max_length=50, null=True)),
                ('relative', models.CharField(max_length=50, null=True)),
                ('control', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Control')),
                ('sujeto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
            ],
        ),
    ]
