# Generated by Django 2.0.4 on 2018-08-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0068_auto_20180824_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campostagimg',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='campostagimg',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Campostagimg',
        ),
        migrations.DeleteModel(
            name='Tagsdicom',
        ),
        migrations.DeleteModel(
            name='Tipoimagenes',
        ),
    ]
