# Generated by Django 2.0.4 on 2018-08-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0069_auto_20180824_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosimg',
            name='sujeto',
        ),
        migrations.RemoveField(
            model_name='parametrosimgcontrol',
            name='sujeto',
        ),
        migrations.DeleteModel(
            name='Parametrosimg',
        ),
        migrations.DeleteModel(
            name='Parametrosimgcontrol',
        ),
    ]
