# Generated by Django 2.0.4 on 2018-08-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0070_auto_20180824_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrosmotioncorrect',
            old_name='absolute',
            new_name='absolute_dwi',
        ),
        migrations.RenameField(
            model_name='parametrosmotioncorrect',
            old_name='relative',
            new_name='absolute_func',
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='graphic_desplazamiento_dwi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='graphic_desplazamiento_func',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='graphic_rotacion_dwi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='graphic_rotacion_func',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='graphic_traslacion_dwi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='graphic_traslacion_func',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='relative_dwi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='relative_func',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
