# Generated by Django 2.0.4 on 2018-08-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0071_auto_20180825_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='aceptado_dwi',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='parametrosmotioncorrect',
            name='aceptado_func',
            field=models.NullBooleanField(),
        ),
    ]
