# Generated by Django 2.0.4 on 2018-10-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0072_auto_20180827_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura_resonancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fracturas', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('fracturas_localizacion', models.CharField(blank=True, max_length=300, null=True)),
                ('hemorragia_subaracnoidea', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('hemorragia_subaracnoidea_mayor_menor', models.CharField(blank=True, choices=[('Mayor a 3 mm', 'Mayor a 3 mm'), ('Menor a 3 mm', 'Menor a 3 mm')], max_length=50, null=True)),
                ('hemorragia_subaracnoidea_sangrado', models.NullBooleanField()),
                ('hemorragia_subaracnoidea_coagulos', models.NullBooleanField()),
                ('hemorragia_subaracnoidea_hemorragia', models.NullBooleanField()),
                ('hemorragia_subaracnoidea_cronico', models.NullBooleanField()),
                ('hematoma_extra', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('hematoma_extra_sub_epi', models.CharField(blank=True, choices=[('Subdural', 'Subdural'), ('Epidural', 'Epidural')], max_length=50, null=True)),
                ('hematoma_extra_espesor', models.CharField(blank=True, max_length=3, null=True)),
                ('hematoma_extra_agudo', models.NullBooleanField()),
                ('hematoma_intra', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('hematoma_intra_mayor_menor', models.CharField(blank=True, choices=[('Volumen mayor a 30 cc', 'Volumen mayor a 30 cc'), ('Volumen menor a 30 cc', 'Volumen menor a 30 cc')], max_length=50, null=True)),
                ('hematoma_intra_localizacion', models.CharField(blank=True, max_length=300, null=True)),
                ('contusion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('contusion_hemorragica', models.CharField(blank=True, choices=[('Hemorrágica', 'Hemorrágica'), ('No Hemorrágica', 'No Hemorrágica')], max_length=50, null=True)),
                ('contusion_cortical', models.CharField(blank=True, choices=[('Cortical', 'Cortical'), ('Subcortical', 'Subcortical')], max_length=50, null=True)),
                ('contusion_localizacion', models.CharField(blank=True, max_length=300, null=True)),
                ('contusion_diametro', models.CharField(blank=True, max_length=3, null=True)),
                ('linea', models.CharField(blank=True, choices=[('Central', 'Central'), ('Desviación', 'Desviación')], max_length=50, null=True)),
                ('linea_tipo', models.CharField(blank=True, choices=[('Menor a 5 mm', 'Menor a 5 mm'), ('Mayor a 5 mm', 'Mayor a 5 mm'), ('Mayor a 10 mm', 'Mayor a 10 mm')], max_length=50, null=True)),
                ('linea_lateralizacion', models.CharField(blank=True, choices=[('Derecha', 'Derecha'), ('Izquierda', 'Izquierda')], max_length=50, null=True)),
                ('herniacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('herniacion_tipo', models.CharField(blank=True, choices=[('Sulbfalcinea', 'Sulbfalcinea'), ('Transtentorial', 'Transtentorial'), ('Uncal', 'Uncal'), ('Amigdalina', 'Amigdalina')], max_length=50, null=True)),
                ('oclusion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('oclusion_tipo', models.CharField(blank=True, choices=[('Arterial', 'Arterial'), ('Venosa', 'Venosa')], max_length=50, null=True)),
                ('oclusion_localizacion', models.CharField(blank=True, max_length=300, null=True)),
                ('edema', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('edema_tipo', models.CharField(blank=True, choices=[('Cito Toxico', 'Cito Toxico'), ('Vasogénico', 'Vasogénico'), ('Intersticial', 'Intersticial')], max_length=50, null=True)),
                ('edema_localizacion', models.CharField(blank=True, max_length=300, null=True)),
                ('infarto_isquemia', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('infarto_isquemia_localizacion', models.CharField(blank=True, max_length=300, null=True)),
                ('lesion_subcortical', models.NullBooleanField()),
                ('lesion_calloso', models.NullBooleanField()),
                ('lsion_dorsolateral', models.NullBooleanField()),
                ('ventriculomegalia', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('vectriculomegalia_actividad', models.NullBooleanField()),
                ('lesiones_asociadas', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('lesiones_asociadas_descripcion', models.TextField(blank=True, null=True)),
                ('atrofia', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('atrofia_descripcion', models.TextField(blank=True, null=True)),
                ('cambios', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=12, null=True)),
                ('cambios_localizacion', models.CharField(blank=True, max_length=300, null=True)),
                ('impresion', models.TextField(blank=True, null=True)),
                ('candidato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato')),
            ],
            options={
                'permissions': (('can_ver_lectura', 'puede ver lectura'),),
            },
        ),
    ]
