# Generated by Django 2.0.4 on 2018-10-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0073_lectura_resonancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='otro1_dt',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='otro1_nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='otro2_dt',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='otro2_nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lectura_resonancia',
            name='linea',
            field=models.CharField(choices=[('Central', 'Central'), ('Desviación', 'Desviación')], max_length=50, null=True),
        ),
    ]
