# Generated by Django 2.0.4 on 2018-10-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0074_auto_20181006_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura_resonancia',
            name='control',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Control'),
        ),
        migrations.AlterField(
            model_name='lectura_resonancia',
            name='candidato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato'),
        ),
    ]
