# Generated by Django 2.0.4 on 2018-10-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0075_auto_20181016_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura_resonancia',
            name='medico_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Medico'),
        ),
    ]
