# Generated by Django 2.0.4 on 2019-01-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0076_lectura_resonancia_medico_responsable'),
        ('taskcelery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskc',
            name='control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Control'),
        ),
        migrations.AddField(
            model_name='taskc',
            name='proceso',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskc',
            name='sujeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Candidato'),
        ),
    ]
