# Generated by Django 2.0.4 on 2019-01-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcelery', '0002_auto_20190118_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskc',
            name='estado',
            field=models.CharField(default='No Creado', max_length=50),
        ),
    ]
