# Generated by Django 2.0.4 on 2019-01-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskcelery', '0003_taskc_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskc',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='validacion.Pipeline'),
        ),
    ]
