# Generated by Django 2.0.3 on 2018-04-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='nombrepersona',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
