# Generated by Django 2.0.4 on 2018-05-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
