# Generated by Django 2.0.4 on 2018-05-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_picture_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='anonimo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
