# Generated by Django 2.0.4 on 2019-03-18 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('validacion', '__first__'),
        ('fileupload', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=200, null=True)),
                ('eliminable', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesamiento.Pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pathscript', models.CharField(max_length=150)),
                ('habilitado', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesamiento.Task')),
                ('tipo_imagen', models.ForeignKey(on_delete=None, to='validacion.Tipoimagenes')),
            ],
        ),
        migrations.CreateModel(
            name='task_celery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.Pipeline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taskgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=200, null=True)),
                ('eliminable', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesamiento.Taskgroup')),
                ('task', models.ManyToManyField(blank=True, to='procesamiento.Task')),
                ('tipo_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes')),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='procesamiento.Taskgroup'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tipo_imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes'),
        ),
    ]
