# Generated by Django 2.0.4 on 2019-04-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0003_auto_20190324_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('word_key', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Imagen', 'Imagen'), ('Grafica', 'Grafica'), ('Texto', 'Texto'), ('Archivo nii', 'Archivo nii'), ('Archivo trk', 'Archivo trk'), ('Archivo csv', 'Archivo csv'), ('Ica Component', 'Ica Component')], max_length=40, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.Task')),
            ],
        ),
        migrations.AlterModelOptions(
            name='results',
            options={},
        ),
        migrations.AlterField(
            model_name='results',
            name='tipo',
            field=models.CharField(choices=[('Imagen', 'Imagen'), ('Grafica', 'Grafica'), ('Texto', 'Texto'), ('Archivo nii', 'Archivo nii'), ('Archivo trk', 'Archivo trk'), ('Archivo csv', 'Archivo csv'), ('Ica Component', 'Ica Component')], max_length=40, null=True),
        ),
    ]
