# Generated by Django 2.0.4 on 2019-08-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0004_auto_20190406_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_result',
            name='tipo',
            field=models.CharField(choices=[('Imagen', 'Imagen'), ('Grafica', 'Grafica'), ('Texto', 'Texto'), ('Archivo nii', 'Archivo nii'), ('Archivo trk', 'Archivo trk'), ('Archivo csv', 'Archivo csv'), ('Ica Component', 'Ica Component'), ('Ica Graph', 'Ica Graph')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='tipo',
            field=models.CharField(choices=[('Imagen', 'Imagen'), ('Grafica', 'Grafica'), ('Texto', 'Texto'), ('Archivo nii', 'Archivo nii'), ('Archivo trk', 'Archivo trk'), ('Archivo csv', 'Archivo csv'), ('Ica Component', 'Ica Component'), ('Ica Graph', 'Ica Graph')], max_length=40, null=True),
        ),
    ]
