# Generated by Django 2.0.4 on 2018-08-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campostagimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=75, null=True)),
                ('medidas', models.CharField(blank=True, max_length=50, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('sujeto', models.CharField(blank=True, max_length=15, null=True)),
                ('precision', models.PositiveIntegerField(blank=True, null=True)),
                ('v_esperado', models.CharField(blank=True, max_length=150, null=True)),
                ('cumple', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tagsdicom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tag', models.CharField(max_length=75)),
                ('name_tag', models.CharField(max_length=75)),
                ('key_tag', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoimagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='campostagimg',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes'),
        ),
        migrations.AddField(
            model_name='campostagimg',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tagsdicom'),
        ),
    ]
