# Generated by Django 2.0.4 on 2018-08-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campostagimg',
            name='medidas',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campostagimg',
            name='v_esperado',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='campostagimg',
            name='valor',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='campostagimg',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
