# Generated by Django 2.0.4 on 2018-08-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0002_auto_20180824_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsdicom',
            name='key_tag',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
