# Generated by Django 2.0.4 on 2018-08-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0003_auto_20180824_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campostagimg',
            name='valor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
