# Generated by Django 2.0.4 on 2018-08-25 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0005_auto_20180824_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campos_defecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.PositiveIntegerField(blank=True, null=True)),
                ('v_esperado', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('medidas', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tagsdicom')),
            ],
        ),
    ]
