# Generated by Django 2.0.4 on 2018-08-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0006_campos_defecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campostagimg',
            options={'permissions': (('can_ver_parametrosimg', 'puede ver parametrosimg'),)},
        ),
    ]
