# Generated by Django 2.0.4 on 2018-08-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0007_auto_20180824_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoimagenes',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
    ]
