# Generated by Django 2.0.4 on 2018-08-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0008_tipoimagenes_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoimagenes',
            name='nombre_aux',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
    ]
