# Generated by Django 2.0.4 on 2018-09-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0009_tipoimagenes_nombre_aux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realineacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujeto', models.CharField(blank=True, max_length=15, null=True)),
                ('structural', models.FileField(blank=True, null=True, upload_to='Archivos')),
                ('funcional', models.FileField(blank=True, null=True, upload_to='Archivos')),
                ('tensor', models.FileField(blank=True, null=True, upload_to='Archivos')),
            ],
            options={
                'permissions': (('can_ver_alineacion', 'puede ver alineacion'),),
            },
        ),
    ]
