# Generated by Django 2.0.4 on 2018-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0010_realineacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='realineacion',
            name='funcional_cambio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realineacion',
            name='structural_cambio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realineacion',
            name='tensor_cambio',
            field=models.BooleanField(default=False),
        ),
    ]
