# Generated by Django 2.0.4 on 2018-10-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0012_snr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snr',
            options={'permissions': (('can_ver_snr', 'puede ver snr'),)},
        ),
    ]
