# Generated by Django 2.0.4 on 2018-10-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0013_auto_20181006_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('etapa', models.CharField(choices=[('Preprocesamiento', 'Preprocesamiento'), ('Postprocesamiento', 'Postprocesamiento')], max_length=25, null=True)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='validacion.Pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pathscript', models.CharField(max_length=150)),
                ('pathout', models.CharField(max_length=150)),
                ('habilitado', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='validacion.Task')),
                ('tipo_imagen', models.ForeignKey(on_delete=None, to='validacion.Tipoimagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Taskgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='validacion.Taskgroup')),
                ('tasks', models.ManyToManyField(to='validacion.Task')),
                ('tipo_imagen', models.ForeignKey(on_delete=None, to='validacion.Tipoimagenes')),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='grupos',
            field=models.ManyToManyField(to='validacion.Taskgroup'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tipo_imagen',
            field=models.ForeignKey(on_delete=None, to='validacion.Tipoimagenes'),
        ),
    ]
